bq-dbt-workshop:
  outputs:
    dev:
      dataset: ${GOOGLE_BIGQUERY_DATASET}
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: ${GOOGLE_BIGQUERY_DATASET_LOCATION}
      method: service-account
      priority: interactive
      project: ${GCP_PROJECT_ID}
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
taxi_rides_ny:
  outputs:
    dev:
      dataset: ${GOOGLE_BIGQUERY_DATASET}
      fixed_retries: 1
      location: ${GOOGLE_BIGQUERY_DATASET_LOCATION}
      method: oauth
      priority: interactive
      project: ${GCP_PROJECT_ID}
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
